spring:
  application:
    name: tasks_service
  datasource:
   url: jdbc:postgresql://localhost:5432/training
   username: postgres
   password: root
   
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
   